### PR TITLE
chore: Adds autogen implementation for multi-agent LLM model chat

### PR DESCRIPTION
**Pull request by neelanjan00**

### CODE REVIEW

**Comment by TechKemon** [comment]
Hey, rather than merging into main branch, can you do PR into main/autogen instead ?

**Comment by luv-singh-ai** [comment]
Hey, will merge this after discussion with Bharat (who has worked on autogen earlier)

**Comment by neelanjan00** [comment]
> Hey, rather than merging into main branch, can you do PR into main/autogen instead ?

@luv-singh-ai , there is no `main/autogen` branch I think, do you want me to create one ?

**Comment by luv-singh-ai** [comment]
My bad, I meant into autogen folder. It'll still be main branch.

**Pull request merged**
