### PR TITLE
chore: updates readme for vite frontend app

### PR DESCRIPTION
**Pull request by neelanjan00**
Updates readme for vite frontend app

### CODE REVIEW

**Comment by luv-singh-ai** [comment]
Thanks

**Comment by luv-singh-ai** [comment]
Hey @neelanjan00 , I ran the frontend. few obersavations:
1. regarding supabase: VITE_SUPABASE_API_KEY & VITE_SUPABASE_AUTHORIZATION_TOKEN are the same in this supabase implementation. you can merge them into one. also, do we need to install `@supabase/supabase-js` if we're making an API call?

2. we need to add a few things :
- disclaimer at the bottom 
- google analytics code to track visits

**Comment by neelanjan00** [comment]
> Hey @neelanjan00 , I ran the frontend. few obersavations:
> 
> 1. regarding supabase: VITE_SUPABASE_API_KEY & VITE_SUPABASE_AUTHORIZATION_TOKEN are the same in this supabase implementation. you can merge them into one. also, do we need to install `@supabase/supabase-js` if we're making an API call?
> 2. we need to add a few things :
> 
> * disclaimer at the bottom
> * google analytics code to track visits

Hi Luv, regarding the above comments:
1. IMO we should retain separate ENVs for `VITE_SUPABASE_API_KEY` and `VITE_SUPABASE_AUTHORIZATION_TOKEN`. In our case, they are the same but they need not be the same always. I am guessing that in our case, we are only using the `anon` key without enabling Supabase's authentication; hence, we are required to pass the same key in both the `Authorization` and `apikey` headers.

When They Are Different:
 - Once authentication is enabled and users log in, the `access_token` is dynamically generated for each user.
- The `apikey` remains a constant key tied to the project.

Regarding `@supabase/supabase-js`, I am removing it since we're only doing one API call which is quite straightforward but it will be better to use the client if we add more DB operations in the future.

2. Sure, let's connect on the same whenever you're available.

**Comment by luv-singh-ai** [comment]
> Hey @neelanjan00 , I ran the frontend. few obersavations:
> 
> 1. regarding supabase: VITE_SUPABASE_API_KEY & VITE_SUPABASE_AUTHORIZATION_TOKEN are the same in this supabase implementation. you can merge them into one. also, do we need to install `@supabase/supabase-js` if we're making an API call?
> 2. we need to add a few things :
> 
> * disclaimer at the bottom
> * google analytics code to track visits

To add disclaimer, please see this - 
https://github.com/PeoplePlusAI/Sukoon/commit/3407a4a6993d7c00f2777839b2e0b703094cd9fc

To add google analytics, please check out this commit - 
https://github.com/PeoplePlusAI/Sukoon/commit/68e9ccf12f5cceeeabf9205fa3bd9e2b822b9e6c

**Comment by luv-singh-ai** [comment]
> > Hey @neelanjan00 , I ran the frontend. few obersavations:
> > 
> > 1. regarding supabase: VITE_SUPABASE_API_KEY & VITE_SUPABASE_AUTHORIZATION_TOKEN are the same in this supabase implementation. you can merge them into one. also, do we need to install `@supabase/supabase-js` if we're making an API call?
> > 2. we need to add a few things :
> > 
> > 
> > * disclaimer at the bottom
> > * google analytics code to track visits
> 
> Hi Luv, regarding the above comments:
> 
> 1. IMO we should retain separate ENVs for `VITE_SUPABASE_API_KEY` and `VITE_SUPABASE_AUTHORIZATION_TOKEN`. In our case, they are the same but they need not be the same always. I am guessing that in our case, we are only using the `anon` key without enabling Supabase's authentication; hence, we are required to pass the same key in both the `Authorization` and `apikey` headers.
> 
> When They Are Different:
> 
> * Once authentication is enabled and users log in, the `access_token` is dynamically generated for each user.
> * The `apikey` remains a constant key tied to the project.
> 
> Regarding `@supabase/supabase-js`, I am removing it since we're only doing one API call which is quite straightforward but it will be better to use the client if we add more DB operations in the future.
> 
> 2. Sure, let's connect on the same whenever you're available.

Hey Neelanjan, yeah you're correct. Going forward, the auth token will be unique for each user, so makes sense to have two env variables.
For the second part, can you look at the commits we did mentioned in previous comment(these involve just adding a few lines of code at relevant place). Let me know when you've integrated it.

**Comment by luv-singh-ai** [comment]
Hey, I've added a DockerFile for cloud deployment. Please check if its' correct. also can we put the endpoint `https://sukoon-api.pplus.ai` as environment variable, rather than hardcoding it?

**Comment by neelanjan00** [comment]
> Hey, also use the `https://sukoon-api.pplus.ai` endpoint as environment variable

Added all the changes in this PR: https://github.com/PeoplePlusAI/Sukoon/pull/17

**Pull request merged**
