### PR TITLE
feat: adds frontend vite app

### PR DESCRIPTION
**Pull request by neelanjan00**
adds frontend vite app

### CODE REVIEW

**Review by luv-singh-ai — COMMENTED** [review]
Can you add steps and some explanation in the README file?

**Comment by luv-singh-ai** [comment]
Great job @neelanjan00

**Comment by luv-singh-ai** [comment]
Hey, can you please point me where the vite frontend connects with the backend sukoon.py file?

**Comment by neelanjan00** [comment]
> Hey, can you please point me where the vite frontend connects with the backend sukoon.py file?

Sure, you can find it here: https://github.com/PeoplePlusAI/Sukoon/blob/72c70002680fd1de4923c3dfa551308a0d78f044/frontend-vite/src/containers/landing-page.jsx#L22

**Comment by luv-singh-ai** [comment]
Hey, can you please add it it README the steps to run it?

**Comment by neelanjan00** [comment]
> Hey, can you please add it it README the steps to run it?

Added here: https://github.com/PeoplePlusAI/Sukoon/pull/15

**Pull request merged**
